os:
  linux
language:
  no
dist:
  bionic
before script:
  - sudo snap install git-repo
  - git clone https://github.com/akhilnarang/scripts && cd scripts && sudo bash setup/android_build_env.sh && sudo bash setup/install_android_sdk.bash
  - mkdir OrangeFox && cd OrangeFox
  - repo init --depth=1 -u https://gitlab.com/OrangeFox/Manifest.git -b fox_9.0 -q
  - repo sync -j8 --force-sync -q
  
script:
  - git clone https://github.com/TeamWin/android_device_xiaomi_violet.git device/xiaomi/violet -q
  - git clone https://github.com/PixelExperience-Devices/kernel_xiaomi_sm6150.git kernel/xiaomi/violet -b ten -q
  - source build/envsetup.sh && export ALLOW_MISSING_DEPENDENCIES=true && export LC_ALL="C"
  - lunch omni_violet-eng && mka recoveryimage -q
