os:
  linux
language:
  no
dist:
  bionic
before script:
  - sudo snap install git-repo
  
script:
  - repo init -u https://github.com/Evolution-X/manifest -b ten
  - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags -q
  - git clone https://github.com/Sap1k/device_xiaomi_lavender.git device/xiaomi/lavender -q
  - git clone https://github.com/Sap1k/vendor_xiaomi_lavender.git vendor/xiaomi/lavender -q
  - git clone https://github.com/Sap1k/kernel_sdm660.git kernel/xiaomi/lavender -q
  - . build/envsetup.sh
  - lunch aosp_lavender-userdebug
  - mka bacon -j3
